### PR TITLE
separated hbaseHelper

### PR DESCRIPTION
**Pull request by hthayko**

### CODE REVIEW

**Comment by wilsonianb** [comment]
Can you move the `require('crawler-hbase')`s to the top of the files?

**Comment by wilsonianb** [comment]
Can you push the `crawler-hbase` repository to Github?

**Comment by hthayko** [comment]
crawler hbase exports 2 things:
1. an init(dbUrl) function
2. hbaseUtils object
the second guy is always at the top of the files, whereas the first cannot be as it requires a dbUrl

**Comment by wilsonianb** [comment]
Looks like `crawler-api` and `crawl-reporter` need to be switched to `crawler-hbase`

**Comment by hthayko** [comment]
yup. I am working on that. so are you suggesting having 3 PR's and merging all of them at the same time ? I am ok with that

**Comment by wilsonianb** [comment]
Updating the crawler on npm would break `crawler-api` since it is pinned to `latest`
https://github.com/ripple/crawler-api/blob/master/package.json#L9

I say may as well switch everything while we're at it.

**Comment by hthayko** [comment]
cool, I will create the other two PR's ASAP

**Comment by hthayko** [comment]
Hbase Revolution Brough to you by:
https://github.com/ripple/crawl-reporter/pull/9
https://github.com/ripple/crawler-api/pull/9
https://github.com/ripple/rippled-network-crawler/pull/54

**Comment by wilsonianb** [comment]
LGTM :+1: 
Maybe don't merge until https://github.com/ripple/crawler-api/pull/9 is merged

**Comment by hthayko** [comment]
sure, I would like to merge all three PRs simultaneously

**Pull request merged**
